#!/bin/sh
#
# Initialize the database defined in
# snaplets/postgresql-simple/devel.cfg.
#
# Ensure this file can be sourced by a bash script and uses bash
# variable syntax; e.g., var=value, not var = value.

set -e


setup () {
    echo

    if [[ ! $1 == '-y' ]]
    then
        echo "WARNING: about to destroy the database \"$db\""
        read -p "Are you sure you want to continue? [Y/n] " -n 1 -r
        if [[ ! $REPLY =~ ^[Yy]$ ]]
        then
            echo "Aborting"
            exit 1
        fi
    fi

    dropdb --if-exists $db
    createdb $db
    echo "createdb $db"

    migrations=( 001-projects )

    for m in "${migrations[@]}" ; do
        echo "running db/$m"
        psql -h $host -p $port $db $user < db/$m.sql
    done
}

if [[ $1 != '--test' ]]
then
    # Set up development
    (
        source snaplets/postgresql-simple/devel.cfg
        setup $1
    )
fi

# Set up the test databse
(
    source snaplets/postgresql-simple/test.cfg
    setup "-y"
)
